### ISSUE TITLE
not connecting to backend

### ISSUE THREAD

**Issue by sodyser23** [IUrreta/DatabaseEditor#76]
Hello guys man this all python and everythings are completly not my stuff and i dont know how in the hell i can fix this situation.

 
![Capture](https://github.com/IUrreta/DatabaseEditor/assets/143003569/5216e059-dc08-40e6-83f9-58001cc6996f)

i've got this screenshot from the launch.sh and the log following : 

[2023-08-23T13_44_28_627Z-debug-0.log](https://github.com/IUrreta/DatabaseEditor/files/12420023/2023-08-23T13_44_28_627Z-debug-0.log)

i'm dont know shit about coding and everythings i've done installation like recomanded.

**Comment by IUrreta** [comment]
Hey, are you trying to execute it on linux or windows? On windows you shouldn't use the .sh file

**Comment by sodyser23** [comment]
> Hey, are you trying to execute it on linux or windows? On windows you shouldn't use the .sh file

i'm using windows, i souldn't be on .sh format ?

**Comment by IUrreta** [comment]
> > Hey, are you trying to execute it on linux or windows? On windows you shouldn't use the .sh file
> 
> i'm using windows, i souldn't be on .sh format ?

No, you should use the run.vbs (or launch.bat in the launcher folder) file, not the .sh file, that one is for linux, although it wil probably throw the same error

**Comment by sodyser23** [comment]
Ether way python was installed like asked on guide so i'm kinda comfused to the reason it's not working

**Comment by IUrreta** [comment]
It doesn't seem like a python issue. Sometimes that happen when the internet conmection is not stable. I would recommend deleting the node_modules folder and trying to run it again

**Comment by sodyser23** [comment]
it says the same thing like last time and for me the app is called "launch.sh", is that a problem ?

I haven't modified it.

**Comment by IUrreta** [comment]
No, there is a launcher folder, and inside it there is the launch.bat file

**Comment by IUrreta** [comment]
Actually, I have just released a new version, it may have not being your problem but me being dumb. Try updating and running again WITH LAUNCH.BAT (in the launcher folder) OR RUN.VBS

**Comment by sodyser23** [comment]
tried and still not good sadly but i'm keep looking for a solution too.

**Comment by IUrreta** [comment]
What does the console says when running launch.bat? Please a screenshot would be helpful :)

**Comment by IUrreta** [comment]
Okay, that is a problem with an easy fix! There's a chapter in this guide to install pip manually: https://github.com/IUrreta/DatabaseEditor/wiki/Troubleshoot-guide

**Comment by sodyser23** [comment]
![Capture](https://github.com/IUrreta/DatabaseEditor/assets/143003569/0877db6b-deb1-4bd3-8699-6a28803891a0)

damn almost working

**Comment by sodyser23** [comment]
the save is recognized but not from the app

**Comment by sodyser23** [comment]
Damn yes it work, man i'm retard for all of this coding thanks for the patience.

**Comment by IUrreta** [comment]
Yes! I'm glad it worked!
